# Generated by Django 2.2.5 on 2020-01-24 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('restriction', models.CharField(choices=[('Reasonable', 'Reasonable'), ('Too Restrictive', 'Too Restrictive')], max_length=65)),
                ('jeans', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=65)),
                ('dressshort', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=65)),
                ('attendjeans', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=65)),
                ('attendshorts', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=65)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 1, 24, 21, 15, 37, 543828, tzinfo=utc))),
            ],
        ),
    ]
