# Generated by Django 2.2.5 on 2020-01-23 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appsurvey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 20, 44, 1, 964500, tzinfo=utc)),
        ),
    ]
